project:
  type: website
  output-dir: docs

website:
  title: "Bunny's Maze of Analytics"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cherylbunny
format:
  html:
    theme: cosmo
    css: styles.css



